apiVersion: v1
kind: Service
metadata:
  name: simpleapp-service
spec:
  selector:
    app: simpleapp
  ports:
    - port: 80
      targetPort: 8899
  type: LoadBalancer
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: simpleapp-deployment
spec:
  selector:
    matchLabels:
      app: simpleapp
  replicas: 2
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - name: simpleapp
        image: mondosage/simpleapp:v2.1.amd
        ports:
        - containerPort: 8899